#!/usr/bin/env bash
set -eu

: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${NORNRUNE_MIGRATION_PASSWORD:?NORNRUNE_MIGRATION_PASSWORD is required}"
: "${NORNRUNE_RUNTIME_PASSWORD:?NORNRUNE_RUNTIME_PASSWORD is required}"

psql --set=ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  --set=migration_password="$NORNRUNE_MIGRATION_PASSWORD" \
  --set=runtime_password="$NORNRUNE_RUNTIME_PASSWORD" \
  --set=database_name="$POSTGRES_DB" <<'SQL'
CREATE ROLE nornrune_migrator LOGIN PASSWORD :'migration_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE nornrune_runtime LOGIN PASSWORD :'runtime_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

ALTER DATABASE :"database_name" OWNER TO nornrune_migrator;
REVOKE ALL ON DATABASE :"database_name" FROM PUBLIC;
GRANT CONNECT ON DATABASE :"database_name" TO nornrune_runtime;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
SQL
