// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: options.proto

package frontproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51001,
		Name:          "nornrune.frontend.policy_name",
		Tag:           "bytes,51001,opt,name=policy_name",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51002,
		Name:          "nornrune.frontend.policy_version",
		Tag:           "bytes,51002,opt,name=policy_version",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51003,
		Name:          "nornrune.frontend.cel_expression",
		Tag:           "bytes,51003,opt,name=cel_expression",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51004,
		Name:          "nornrune.frontend.canonical_target",
		Tag:           "bytes,51004,opt,name=canonical_target",
		Filename:      "options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string policy_name = 51001;
	E_PolicyName = &file_options_proto_extTypes[0]
	// optional string policy_version = 51002;
	E_PolicyVersion = &file_options_proto_extTypes[1]
	// optional string cel_expression = 51003;
	E_CelExpression = &file_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string canonical_target = 51004;
	E_CanonicalTarget = &file_options_proto_extTypes[3]
)

var File_options_proto protoreflect.FileDescriptor

const file_options_proto_rawDesc = "" +
	"\n" +
	"\roptions.proto\x12\x11nornrune.frontend\x1a google/protobuf/descriptor.proto:B\n" +
	"\vpolicy_name\x12\x1f.google.protobuf.MessageOptions\x18\xb9\x8e\x03 \x01(\tR\n" +
	"policyName:H\n" +
	"\x0epolicy_version\x12\x1f.google.protobuf.MessageOptions\x18\xba\x8e\x03 \x01(\tR\rpolicyVersion:H\n" +
	"\x0ecel_expression\x12\x1f.google.protobuf.MessageOptions\x18\xbb\x8e\x03 \x01(\tR\rcelExpression:J\n" +
	"\x10canonical_target\x12\x1d.google.protobuf.FieldOptions\x18\xbc\x8e\x03 \x01(\tR\x0fcanonicalTargetB:Z8github.com/sebishogun/nornrune/frontend/proto;frontprotob\x06proto3"

var file_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
}
var file_options_proto_depIdxs = []int32{
	0, // 0: nornrune.frontend.policy_name:extendee -> google.protobuf.MessageOptions
	0, // 1: nornrune.frontend.policy_version:extendee -> google.protobuf.MessageOptions
	0, // 2: nornrune.frontend.cel_expression:extendee -> google.protobuf.MessageOptions
	1, // 3: nornrune.frontend.canonical_target:extendee -> google.protobuf.FieldOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_proto_init() }
func file_options_proto_init() {
	if File_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_proto_rawDesc), len(file_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_options_proto_goTypes,
		DependencyIndexes: file_options_proto_depIdxs,
		ExtensionInfos:    file_options_proto_extTypes,
	}.Build()
	File_options_proto = out.File
	file_options_proto_goTypes = nil
	file_options_proto_depIdxs = nil
}
